name: GoCA Testes

on: [push]

jobs:
  tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.21
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: 1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Tests
      run: make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
