name: GoCA Testes

on: [push]

jobs:
  tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    # TODO: Implement a more consistent test for the docs issue #14
    # - name: Check if API Docs are updated
    #   run: |
    #     export PATH=$PATH:$(go env GOPATH)/bin
    #     cd rest-api
    #     make doc
    #     api_docs=$(git diff --name-only | grep ^docs || true )
    #     if [[ $api_docs != "" ]]; then echo $api_docs; exit 1; fi