name: goca-rest-api

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: my-docker-hub-namespace/my-docker-hub-repository
        tag_with_ref: true

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GPR_TOKEN }}
        registry: docker.pkg.github.com
        repository: kairoaraujo/goca/goca-rest-api
        tag_with_ref: true

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        readme-filepath: ./DOCKER-README.md
        repository: kairoaraujo/goca